### ISSUE TITLE
Allow connecting to console of child processes

### ISSUE THREAD

**Issue by jstoneham** [redjack/rflow#66]
Debugging with pry-debugger is impossible in RFlow 1 because all the child processes are detached from console. It would be really nice if we were able to fix that.

Idea:
1) have each child process create 2 FIFOs in the rflow directory, a lot like the IPC sockets, maybe named after its name or its PID
2) child process connects stdout to one and stdin to another, instead of /dev/null
3) provide a command-line utility that does the equivalent of tailing one and catting to the other
4) so you could run that command-line utility and then cause pry-debugger to fire and it would hook up

cf. http://stackoverflow.com/questions/4273977/how-do-you-connect-the-keyboard-and-a-named-pipe-to-stdin-in-bash

**Comment by jstoneham** [comment]
Oh, and right now if you run pry-debugger it fries processes and stuff doesn't go down well. Fix that issue in general and then make sure that things are handled sensibly in the event that pry-debugger can't load because no console is connected.

**Comment by rajones47** [comment]
# Possible solution - using pry-remote

I combined these gems:
* pry
* pry-debugger
* pry-remote
* pry-stack_explorer (for good measure)

The gems were added to the Gemfile.  The require  in the relevant rb file for above gems and added a line with `binding.remote_pry` inserted in code at a desired breakpoint, I was able to start an RFlow app and jump in at a break point using `pry-remote` from the command line.

I have done limited testing, inspecting variables, stepping and successfully continuing execution from within RFlow itself as well as RFlow extensions as found in the http_logger example.  More exploration is required here.

## Limitations

pry-debugger uses debugger which is limited to Ruby version 1.  

### Versions

Successful testing here has only been done with Ruby 1.9.3.

There is no clear path for Ruby 2 (MRI 2.0.0 +).  The *debugger* gem is **not** compatible with Ruby 2.  There is a *debugger2* but that doesn't seem to work very well (testing and web digging).  

Someone offered to help with debugger for Ruby 2 and the help was rejected (essentially) this resulted in a fork of debugger called `byebug` that works with Ruby 2.  However, there are mixed results on the web and my testing wasn't encouraging.  I could get to a breakpoint, connect with `pry-remote` and inspect stuff but execution would not continue after that, it just hung.

**Comment by jstoneham** [comment]
So, we found a different way to debug, which removes the need to do this console jiggery pokery directly. At least under Ruby 2, straight up `byebug` will do the trick. The tricky bit is, because we do our own forking instead of having some manager server spin up multiple processes, you can't start the debugger early, because all the processes will try to sit on the same port (which doesn't fail as loudly as you'd like).

Step 1: add `gem 'byebug'` to Gemfile
Step 2: When you want to set a debug point, run something like: `remote_byebug 'localhost', 8989 + worker.index` (`worker.index` is a quick and dirty attempt at making the port differ by process in case you have multiple workers on a shard wandering around; you probably also want to log the port you're using). You'll be stopped at a breakpoint.
Step 3: Fire up `byebug -R localhost:<port>`. Voila.
Step 4: Leave byebug open when you're done with it, if you hit the breakpoint again it's going to assume it's still connected, and if it isn't, you can't seem to reconnect.
