### ISSUE TITLE
When temp pidfile already exists, RFlow hangs at daemonizing

### ISSUE THREAD

**Issue by mlartz** [redjack/rflow#67]
If a tmp pidfile already exists (e.g. run/.rflow.pid), RFlow appears to start but hangs when daemonizing.  The current logic retries the tmp pidfile creation forever, without issuing any notification to the user that a tmp pidfile already exists.  We should either log this event, cap the number of retries, and/or do something better.

https://github.com/redjack/rflow/blob/master/lib/rflow/pid_file.rb#L20
```ruby
pid_fp = begin
           tmp_path = File.join(File.dirname(path), ".#{File.basename(path)}")
           File.open(tmp_path, File::RDWR|File::CREAT|File::EXCL, 0644)
         rescue Errno::EEXIST
           retry
         end
```

**Comment by jstoneham** [comment]
In one case, we saw this because our partition ran out of space.

**Comment by jstoneham** [comment]
We think this may have to do with the pidfile being 0 bytes.

**Comment by rajones47** [comment]
In RFlow::PIDFIle

https://github.com/redjack/rflow/blob/master/lib/rflow/pid_file.rb#L22

when the temporary hidden pidfile is present, File.open(tmp_path, ... ) throws exception Errno::EEXIST and a the rescue block is retried.  The temp hidden file is not going anywhere by itself, so either it needs to be discovered and removed and a warning logged, or just an error logged and printed and the code exits.

At this point the pidfile has already been checked and it has been verified that the app is not currently running (to the extent it can be portably with the pidfile method.)  So it is probably safe to automatically remove the temporary hidden pidfile at tmp_path and proceed creating a new pidfile.
