### ISSUE TITLE
More infinite retry loop problems

### ISSUE THREAD

**Issue by jstoneham** [redjack/rflow#68]
Got an infinite retry loop when the app tried to quit, but a file exporter was stuck in a loop:
NoMethodError: undefined method `send_msg' for nil:NilClass, retrying send

**Comment by jstoneham** [comment]
This happened when #configure! in another component threw a NameError.

**Comment by rajones47** [comment]
OBE
This issue is likely solved in issue #57 by preventing retry on exception when sending.
The NameError described happened due to a misspelled variable name.
